import { Stock } from "./types";

export const SECTORS = [
  "Financial",
  "Tech",
  "Consumer",
  "Power",
  "Pipe",
  "Others",
];

export const MOCK_STOCKS: Stock[] = [
  {
    symbol: "AFFLE",
    name: "Affle India",
    sector: "Tech",
    buyPrice: 1295.0,
    quantity: 20,
    cmp: 1468.9,
    peRatio: 54.2,
    eps: 27.1,
    latestEarningsQuarter: "Q1 FY27",
    latestEarningsCr: 92,
  },
  {
    symbol: "BAJFINANCE",
    name: "Bajaj Finance",
    sector: "Financial",
    buyPrice: 7240.0,
    quantity: 7,
    cmp: 6874.14,
    peRatio: 28.9,
    eps: 238.2,
    latestEarningsQuarter: "Q1 FY27",
    latestEarningsCr: 4765,
  },
  {
    symbol: "HDFCBANK",
    name: "HDFC Bank",
    sector: "Financial",
    buyPrice: 1518.41,
    quantity: 32,
    cmp: 1682.75,
    peRatio: 18.7,
    eps: 90.1,
    latestEarningsQuarter: "Q1 FY27",
    latestEarningsCr: 16175,
  },
  {
    symbol: "ICICIBANK",
    name: "ICICI Bank",
    sector: "Financial",
    buyPrice: 966.51,
    quantity: 45,
    cmp: 1218.36,
    peRatio: 19.4,
    eps: 62.8,
    latestEarningsQuarter: "Q1 FY27",
    latestEarningsCr: 11696,
  },
  {
    symbol: "KPITTECH",
    name: "KPIT Tech",
    sector: "Tech",
    buyPrice: 1438.0,
    quantity: 25,
    cmp: 1765.44,
    peRatio: 61.3,
    eps: 28.8,
    latestEarningsQuarter: "Q1 FY27",
    latestEarningsCr: 204,
  },
  {
    symbol: "LTIM",
    name: "LTI Mindtree",
    sector: "Tech",
    buyPrice: 5520.0,
    quantity: 9,
    cmp: 5248.56,
    peRatio: 31.6,
    eps: 166.1,
    latestEarningsQuarter: "Q1 FY27",
    latestEarningsCr: 1254,
  },
  {
    symbol: "POLYCAB",
    name: "Polycab",
    sector: "Pipe",
    buyPrice: 5230.0,
    quantity: 8,
    cmp: 6682.25,
    peRatio: null, // demonstrates the "missing P/E" state
    eps: null, // demonstrates the "missing earnings" state
    latestEarningsQuarter: null,
    latestEarningsCr: null,
  },
  {
    symbol: "SUZLON",
    name: "Suzlon",
    sector: "Power",
    buyPrice: 45.2,
    quantity: 600,
    cmp: 62.8,
    peRatio: 44.6,
    eps: 1.41,
    latestEarningsQuarter: "Q1 FY27",
    latestEarningsCr: 302,
  },
  {
    symbol: "TATAPOWER",
    name: "Tata Power",
    sector: "Power",
    buyPrice: 318.5,
    quantity: 110,
    cmp: 438.15,
    peRatio: 37.1,
    eps: 11.8,
    latestEarningsQuarter: "Q1 FY27",
    latestEarningsCr: 1189,
  },
  {
    symbol: "TATATECH",
    name: "Tata Technologies",
    sector: "Tech",
    buyPrice: 1120.0,
    quantity: 24,
    cmp: 1018.71,
    peRatio: 42.8,
    eps: 23.8,
    latestEarningsQuarter: "Q1 FY27",
    latestEarningsCr: 162,
  },
];
